import { Translations } from './types';

export const fmt = (n: number) => parseFloat(n.toFixed(1)).toString();

export const translations: Translations = {
  dr: { // Darija
    appTitle: "MBERATEX",
    subTitle: "حساب سعر التكلفة (Prix de Revient)",
    modelInfo: "معلومات الموديل & التكلفة",
    modelName: "اسم الموديل",
    sewingTime: "وقت الخياطة (دقيقة)",
    costMinute: "تكلفة الدقيقة",
    cutting: "فصالة",
    packing: "تغليف (Emballage)",
    totalTime: "المجموع",
    materials: "السلعة (Matière Première)",
    matName: "المادة",
    price: "الثمن",
    qtyUnit: "الكمية / الوحدة",
    total: "المجموع",
    addMat: "إضافة مادة",
    needs: "تقدير احتياجات الطلبية",
    needsDesc: "حساب السلعة + الميزانية",
    waste: "الخسارة (Waste)",
    orderQty: "الكمية المطلوبة",
    toBuy: "للشراء",
    realBudget: "ميزانية السلعة (Real)",
    theoCost: "تكلفة السلعة (النظري)",
    laborCost: "تكلفة اليد العاملة",
    totalBudget: "الميزانية الإجمالية",
    totalCost: "التكلفة الكلية",
    settings: "إعدادات الهوامش والضريبة",
    apply: "تطبيق",
    margeAtelier: "ربح المصنع %",
    tva: "الضريبة %",
    margeBoutique: "ربح المحل %",
    ticketTitle: "بطاقة التكلفة",
    docTitle: "ورقة تقنية (A4)",
    date: "التاريخ",
    totalMat: "مجموع السلعة",
    labor: "اليد العاملة",
    costPrice: "سعر التكلفة (P.R)",
    prodCost: "تكلفة الإنتاج",
    sellHT: "ثمن البيع (HT)",
    sellTTC: "ثمن البيع (TTC)",
    netProfit: "الربح الصافي",
    shopPrice: "ثمن المحل",
    print: "طباعة",
    excel: "تحميل Excel",
    pdf: "إعدادات PDF",
    auto: "أوتو",
    manual: "يدوي",
    companyName: "اسم الشركة (اضغط للتعديل)",
    companyAddress: "العنوان ورقم الهاتف...",
    companyLegal: "ICE: 000... | RC: 000... (المعلومات القانونية)",
    notes: "ملاحظات إضافية...",
    ref: "المرجع",
    viewTicket: "بطاقة",
    viewDoc: "وثيقة A4",
    uploadLogo: "اضغط لرفع اللوغو",
    pdfSettings: "إعدادات الطباعة PDF",
    orientation: "الاتجاه",
    portrait: "عمودي (عادي)",
    landscape: "أفقي (90 درجة)",
    colorMode: "الألوان",
    color: "ألوان (Color)",
    grayscale: "أبيض وأسود (N&B)",
    zoom: "الحجم (Echelle)",
    cancel: "إلغاء",
    download: "تحميل الآن",
    preview: "معاينة (Aperçu)",
    generating: "جاري التحضير...",
    orderNeedsTitle: "احتياجات الطلبية (Commande)",
    qtyToBuy: "الكمية للشراء",
    totalLine: "المجموع",
    loadingLib: "جاري تحميل النظام..."
  },
  fr: {
    appTitle: "Calculateur de Coûts",
    subTitle: "Calcul de Prix de Revient Industriel",
    modelInfo: "Infos Modèle & Coûts",
    modelName: "Nom du Modèle",
    sewingTime: "Temps Couture (min)",
    costMinute: "Coût Minute",
    cutting: "Coupe",
    packing: "Emballage",
    totalTime: "Total",
    materials: "Matières Premières",
    matName: "Matière",
    price: "Prix",
    qtyUnit: "Qté / Unité",
    total: "Total",
    addMat: "Ajouter Matière",
    needs: "Estimation des Besoins",
    needsDesc: "Calcul Matière + Budget",
    waste: "Majoration (Perte)",
    orderQty: "Qté Commande",
    toBuy: "À Acheter",
    realBudget: "Budget Matière (Réel)",
    theoCost: "Coût Matière (Théo)",
    laborCost: "Coût Main d'œuvre",
    totalBudget: "Budget Total",
    totalCost: "Coût Global",
    settings: "Marges & Taxes",
    apply: "Appliquer",
    margeAtelier: "Marge Atelier %",
    tva: "TVA %",
    margeBoutique: "Marge Boutique %",
    ticketTitle: "Fiche de Revient",
    docTitle: "Fiche Technique (A4)",
    date: "Date",
    totalMat: "Total Matière",
    labor: "Main d'œuvre",
    costPrice: "Prix de Revient",
    prodCost: "Coût de Production",
    sellHT: "Prix Vente (HT)",
    sellTTC: "Prix Vente (TTC)",
    netProfit: "Marge Nette",
    shopPrice: "Prix Boutique",
    print: "Imprimer",
    excel: "Télécharger Excel",
    pdf: "Config PDF",
    auto: "Auto",
    manual: "Manuel",
    companyName: "Nom de la Société (Cliquer pour éditer)",
    companyAddress: "Adresse et Téléphone...",
    companyLegal: "ICE: 000... | RC: 000... (Infos Légales)",
    notes: "Notes supplémentaires...",
    ref: "Réf",
    viewTicket: "Ticket",
    viewDoc: "Document A4",
    uploadLogo: "Cliquer pour Logo",
    pdfSettings: "Paramètres PDF",
    orientation: "Orientation",
    portrait: "Portrait",
    landscape: "Paysage (90°)",
    colorMode: "Couleurs",
    color: "Couleur",
    grayscale: "Noir & Blanc",
    zoom: "Échelle",
    cancel: "Annuler",
    download: "Télécharger",
    preview: "Aperçu",
    generating: "Génération...",
    orderNeedsTitle: "Besoins pour la Commande",
    qtyToBuy: "Qté à Acheter",
    totalLine: "Total Ligne",
    loadingLib: "Chargement..."
  },
  en: {
    appTitle: "Industrial Cost Calculator",
    subTitle: "Cost Price Calculation",
    modelInfo: "Model Info & Costs",
    modelName: "Model Name",
    sewingTime: "Sewing Time (min)",
    costMinute: "Cost per Minute",
    cutting: "Cutting",
    packing: "Packing",
    totalTime: "Total",
    materials: "Raw Materials",
    matName: "Material",
    price: "Price",
    qtyUnit: "Qty / Unit",
    total: "Total",
    addMat: "Add Material",
    needs: "Order Needs Estimation",
    needsDesc: "Material Calc + Budget",
    waste: "Waste %",
    orderQty: "Order Qty",
    toBuy: "To Buy",
    realBudget: "Material Budget (Real)",
    theoCost: "Material Cost (Theo)",
    laborCost: "Labor Cost",
    totalBudget: "Total Budget",
    totalCost: "Total Cost",
    settings: "Margins & Taxes",
    apply: "Apply",
    margeAtelier: "Factory Margin %",
    tva: "VAT %",
    margeBoutique: "Shop Margin %",
    ticketTitle: "Cost Sheet",
    docTitle: "Technical Sheet (A4)",
    date: "Date",
    totalMat: "Total Materials",
    labor: "Labor",
    costPrice: "Cost Price",
    prodCost: "Production Cost",
    sellHT: "Sale Price (Ex. Tax)",
    sellTTC: "Sale Price (Inc. Tax)",
    netProfit: "Net Profit",
    shopPrice: "Retail Price",
    print: "Print",
    excel: "Download Excel",
    pdf: "PDF Setup",
    auto: "Auto",
    manual: "Manual",
    companyName: "Company Name...",
    companyAddress: "Address & Phone...",
    companyLegal: "ICE: 000... | RC: 000...",
    notes: "Additional notes...",
    ref: "Ref",
    viewTicket: "Ticket",
    viewDoc: "A4 Doc",
    uploadLogo: "Click for Logo",
    pdfSettings: "PDF Settings",
    orientation: "Orientation",
    portrait: "Portrait",
    landscape: "Landscape",
    colorMode: "Color Mode",
    color: "Color",
    grayscale: "Grayscale",
    zoom: "Scale",
    cancel: "Cancel",
    download: "Download",
    preview: "Preview",
    generating: "Generating...",
    orderNeedsTitle: "Order Requirements",
    qtyToBuy: "Qty to Buy",
    totalLine: "Line Total",
    loadingLib: "Loading..."
  },
  es: {
    appTitle: "Calculadora de Costos",
    subTitle: "Cálculo de Precio de Coste",
    modelInfo: "Info Modelo y Costos",
    modelName: "Nombre del Modelo",
    sewingTime: "Tiempo Costura (min)",
    costMinute: "Costo por Minuto",
    cutting: "Corte",
    packing: "Embalaje",
    totalTime: "Total",
    materials: "Materias Primas",
    matName: "Material",
    price: "Precio",
    qtyUnit: "Cant. / Unidad",
    total: "Total",
    addMat: "Añadir Material",
    needs: "Estimación de Necesidades",
    needsDesc: "Cálculo Material + Presupuesto",
    waste: "Desperdicio %",
    orderQty: "Cant. Pedido",
    toBuy: "A Comprar",
    realBudget: "Presupuesto Mat. (Real)",
    theoCost: "Costo Mat. (Teórico)",
    laborCost: "Costo Mano de Obra",
    totalBudget: "Presupuesto Total",
    totalCost: "Costo Global",
    settings: "Márgenes e Impuestos",
    apply: "Aplicar",
    margeAtelier: "Margen Fábrica %",
    tva: "IVA %",
    margeBoutique: "Margen Tienda %",
    ticketTitle: "Hoja de Costos",
    docTitle: "Ficha Técnica (A4)",
    date: "Fecha",
    totalMat: "Total Materiales",
    labor: "Mano de Obra",
    costPrice: "Precio de Coste",
    prodCost: "Costo de Producción",
    sellHT: "Precio Venta (S. Imp)",
    sellTTC: "Precio Venta (C. Imp)",
    netProfit: "Beneficio Neto",
    shopPrice: "Precio Tienda",
    print: "Imprimir",
    excel: "Descargar Excel",
    pdf: "Config PDF",
    auto: "Auto",
    manual: "Manual",
    companyName: "Nombre Empresa...",
    companyAddress: "Dirección y Teléfono...",
    companyLegal: "ICE: 000... | RC: 000...",
    notes: "Notas adicionales...",
    ref: "Ref",
    viewTicket: "Ticket",
    viewDoc: "Doc A4",
    uploadLogo: "Clic para Logo",
    pdfSettings: "Configuración PDF",
    orientation: "Orientación",
    portrait: "Vertical",
    landscape: "Horizontal",
    colorMode: "Color",
    color: "Color",
    grayscale: "Blanco y Negro",
    zoom: "Escala",
    cancel: "Cancelar",
    download: "Descargar",
    preview: "Vista Previa",
    generating: "Generando...",
    orderNeedsTitle: "Necesidades del Pedido",
    qtyToBuy: "Cant. a Comprar",
    totalLine: "Total Línea",
    loadingLib: "Cargando..."
  }
};